## map()

In [86]:
listA = [1989,1990,1991,1992]
listB =[] #[33,32,31,30]
for item in listA:
    listB.append(2023-item)
print(listB)

[34, 33, 32, 31]


In [89]:
# map
q2 = list(map(lambda x:2023-x,listA))
print(q2)

[34, 33, 32, 31]


In [90]:
# map
q2 = tuple(map(lambda x:2022-x,listA))
print(q2)

(33, 32, 31, 30)


In [91]:
listC = [1,2,3,4,5,6,7,8,9,10]
#[3,6,9,12,15,18,21,24,27,30]

In [92]:
#map(fn,list)
q3 = list(map(lambda x:x*3,listC))
print(q3)

[3, 6, 9, 12, 15, 18, 21, 24, 27, 30]


In [93]:
listD = [11,22,33]
#[21,32,43]

q4 = list(map(lambda x:x+10,listD))
print(q4)

[21, 32, 43]


## filter()

In [6]:

listE = [22,33,44,55,22,33,44,55,66]
listF = []
#[55,55,66]

for item in listE:
    if item > 50:
        listF.append(item)
print(listF)

[55, 55, 66]


In [96]:
# filter 
q5 = list(filter(lambda x:x >= 50,[22,33,44,50,22,33,44,55,66]))
print(q5)

[50, 55, 66]


In [8]:
listG = [33,44,55,22,3,477,88,99]
print(list(filter(lambda x : x%2 == 0,listG))) #even
print(list(filter(lambda x : x%2 != 0,listG))) # odd

[44, 22, 88]
[33, 55, 3, 477, 99]


In [97]:
listF = ["Priyanka","Raj","Ganesh"]
print(list(filter(lambda x : len(x)  == 4,listF)))

[]


### reduce()

In [15]:

listG = [1,2,5,10] # 18
sum = 0    # acc

for item in listG:
    sum = sum + item
print(sum)

18


In [100]:
from functools import reduce

print(reduce(lambda x,y:x+y,listG))

18


In [102]:
# print(reduce(lambda acc,nextval:acc+nextval,listG,5))
#[1,2,5,10] 
#acc 2
#itr 3 5 10 20
print(reduce(lambda x,y:x+y,listG,2))

20


In [103]:
# reduce
def all_sum(x):
    s = 0 
    for i in x:
        s = s + i
    return s

print(all_sum([1,2,3,4,5]))

15


In [105]:
print(reduce(lambda x ,y: x+y ,[1,2,3,4,5]))

print(reduce(lambda x ,y: x*y ,[1,2,3,4,5]))

15
120


##  oops

In [ ]:
oops 

## try ... except

In [107]:
a = 10
#b = 100
b = 0
c = a/b # ZeroDivisionError: division by zero if b = 0
print(c)

print("ok")

ZeroDivisionError: division by zero

In [115]:
try:
    a = 10
    # b = 100
    b = 0
    c = a/b # ZeroDivisionError: division by zero if b = 0
    print(c)
except FileNotFoundError as e:
    print("Some error occured ", e)
except IndexError as e:
    print("Element not found" , e )
except ZeroDivisionError as e:   
    print("You have enterd wrong value of b , should not be zero")

    
print("ok")

You have enterd wrong value of b , should not be zero
ok


In [24]:
try:
    a = 10
    # b = 100
    b = 0
    c = a/b # ZeroDivisionError: division by zero if b = 0
    print(c)
except FileNotFoundError as e:
    print("Some error occured ", e)
except IndexError as e:
    print("Element not found" , e )
except:
    print("Something wrong")

Something wrong


In [25]:
# 1. catch exception in below code using try... except 
# else print " Code Execution was successful"
try:
    list_z = [1,2,3,"a"]
    print(5/1)
    for i in range(3):
        if type(list_z[i]) == int:
            print("This is int")
        
        else:
            print("This is not int") 
except IndexError as e1:
    print("Error occured is:",e1)
except ZeroDivisionError:
    print("input should not be zero")
else:
    print (" Code Execution was successful")
finally:
    print("Code End")

print("Hi")

5.0
This is int
This is int
This is int
 Code Execution was successful
Code End
Hi


In [26]:
# 2. catch exception in below code using try... except
# else print " Code Execution was successful"
# also close the file irrespective of operation on file
try:
    f = open(r"one.txt")
    print(f.read())
except FileNotFoundError as e2:
    print(f"Error occured is:",e2)
else:
    print (" Code Execution was successful")
finally:
    try:
        f.close()
        print("File closed")
    except:
        print("File not found" )

Error occured is: [Errno 2] No such file or directory: 'one.txt'
File not found


In [27]:
# # 3. catch exception in below code using try... except

try:
    print("Hello World)
except :
    print("Error occured is:")   # syntax erroe not handled

SyntaxError: EOL while scanning string literal (3391841874.py, line 4)

### raise Exception 

In [117]:

# user defined exception


x = int(input("Enter an even number !!!"))
if x %2 != 0:
    raise Exception("Enter only even number")
else:
    print("The number is even ")

Enter an even number !!!5


Exception: Enter only even number

# Numpy


In [120]:
import numpy as np   # call
#      library  alias

In [124]:
# Create a 1D array
a = np.array([1, 2, 3])
print(a)
type(a)

[1 2 3]


numpy.ndarray

In [123]:
a = numpy.array([1, 2, 3])

NameError: name 'numpy' is not defined

In [132]:
z = [1,2,3,4,5,6,7,8,9]
print(z)
print(type(z))

[1, 2, 3, 4, 5, 6, 7, 8, 9]
<class 'list'>


In [134]:
b = np.array([2,3,4])
b

array([2, 3, 4])

In [135]:
b = np.array(z)
print(type(b))

<class 'numpy.ndarray'>


In [136]:
print(z)   # list
print(b)   # array

[1, 2, 3, 4, 5, 6, 7, 8, 9]
[1 2 3 4 5 6 7 8 9]


In [137]:
z*2

[1, 2, 3, 4, 5, 6, 7, 8, 9, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [138]:
b*2

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18])

In [180]:
a = np.array([1, 2, 3, 4, 5])
a

array([1, 2, 3, 4, 5])

In [181]:
b = np.array([1, 4,6,8,8])

In [182]:
a+b

array([ 2,  6,  9, 12, 13])

In [10]:
a = "My name is \n Raj"
a

'My name is \n Raj'

In [11]:
print(a)

My name is 
 Raj


In [140]:
# Get the shape of an array
print(a.shape)

(5,)


float64


In [63]:
# Get the number of dimensions of an array
print(a.ndim)

1


In [45]:
# Creating arrays

# 1D array
a1 = np.arange(15) # same as range 
print(a1)
print(type(a1))

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
<class 'numpy.ndarray'>


In [144]:
a1 = np.arange(5) # same as range 
print(a1)
print(type(a1))

[0 1 2 3 4]
<class 'numpy.ndarray'>


In [145]:
# Create a 2D array
b = np.array([[1, 2, 3], [4, 5, 6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [146]:
#2D array

z2 = [[1,2,3,4,5,6,7,8,9] , [1,2,3,4,5,6,7,8,9]]
a = np.array(z2)
print(a)
print(type(a))

[[1 2 3 4 5 6 7 8 9]
 [1 2 3 4 5 6 7 8 9]]
<class 'numpy.ndarray'>


In [147]:
# Get the shape of an array
print(a.shape)

(2, 9)


int32


In [149]:
# Get the number of dimensions of an array
print(a.ndim)

2


In [150]:
# creating array 

a = np.arange(10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [151]:
a = np.arange(15,25)
print(a)

[15 16 17 18 19 20 21 22 23 24]


In [152]:
a = np.arange(0,100)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]


In [153]:
# np.arange(start,stop,stepsize)
a = np.arange(0,100,5)
print(a)

[ 0  5 10 15 20 25 30 35 40 45 50 55 60 65 70 75 80 85 90 95]


In [154]:
a = np.arange(0,100,10)
print(a)

[ 0 10 20 30 40 50 60 70 80 90]


In [157]:
a = list(range(0,100,0.5))
print(a)

TypeError: 'float' object cannot be interpreted as an integer

In [155]:
a = np.arange(0,10,.5) # fractional step count is allowed 
print(a)

[0.  0.5 1.  1.5 2.  2.5 3.  3.5 4.  4.5 5.  5.5 6.  6.5 7.  7.5 8.  8.5
 9.  9.5]


In [ ]:
# reshape to convert the array dimension
# 2D array

In [158]:
a = np.arange(15)

In [159]:
a 

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

In [160]:
a = np.arange(15).reshape(1,15)
print(a)

[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]]


In [161]:
a = np.arange(15).reshape(2,7)
print(a)

ValueError: cannot reshape array of size 15 into shape (2,7)

In [162]:
a = np.arange(16)
print(a)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15]


In [165]:
a = np.arange(16).reshape(2,8)
print(a)

[[ 0  1  2  3  4  5  6  7]
 [ 8  9 10 11 12 13 14 15]]


In [166]:
a = np.arange(16).reshape(4,4)
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]
 [12 13 14 15]]


In [168]:
a = np.array([[1,2,3,4],[5,6,7,8],[9,10,11,12],[13,14,15,16]]) # Matrix of 4x4
print(a)

[[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]
 [13 14 15 16]]


In [169]:
a = a.reshape(2,8) # Reshape 2x8
print(a)

[[ 1  2  3  4  5  6  7  8]
 [ 9 10 11 12 13 14 15 16]]


In [170]:
a = a.reshape(8,2) # Reshape 2x8
print(a)

[[ 1  2]
 [ 3  4]
 [ 5  6]
 [ 7  8]
 [ 9 10]
 [11 12]
 [13 14]
 [15 16]]


In [171]:
# using tuple
z1 = (1,2,3,4,5,6,7,8,9)
a1 = np.array(z1)
print(a1)
print(type(a1)) #<class 'numpy.ndarray'>

[1 2 3 4 5 6 7 8 9]
<class 'numpy.ndarray'>


In [172]:
# creating 1d array

a1 = np.array([1,2,3,4,5,6,7,8,9])
print(a1)

[1 2 3 4 5 6 7 8 9]


In [173]:
a2 = np.array([[1,2,3,4,5,6,7,8,9],[1,2,3,4,5,6,7,8,9]])
print(a2)

[[1 2 3 4 5 6 7 8 9]
 [1 2 3 4 5 6 7 8 9]]


In [71]:
# creating 3d array
a3 = np.array([[[1,2,3,4,5,6,7,8,9],[1,2,3,4,5,6,7,8,9],[1,2,3,4,5,6,7,8,9],[1,2,3,4,5,6,7,8,9]]])
print(a3)

[[[1 2 3 4 5 6 7 8 9]
  [1 2 3 4 5 6 7 8 9]
  [1 2 3 4 5 6 7 8 9]
  [1 2 3 4 5 6 7 8 9]]]


In [72]:
print(a1.ndim) 
print(a2.ndim)
print(a3.ndim) # x/y/z axis count

1
2
3


In [74]:
a2 = np.array([[1.0,2,3,4,5,6,7,8,9],[1,2,3,4,5,6,7,8,9]])
print(a2.dtype.name)
print(a2)

float64
[[1. 2. 3. 4. 5. 6. 7. 8. 9.]
 [1. 2. 3. 4. 5. 6. 7. 8. 9.]]


In [ ]:
# a2 = np.array([['1',2,3,4,5,6,7,8,9],[1,2,3,4,5,6,7,8,9]])
# print(a2.dtype.name)
# print(a2)

print(a2.size) # elements count
print(a1.size)
print(a3.size)

In [75]:
z = np.zeros([5,3])
print(z)

[[0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]
 [0. 0. 0.]]


array([0., 0., 0.])

In [76]:
o = np.ones([5,3])
print(o)

[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


In [77]:
d = np.eye(5)
print(d)

[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


In [175]:
# copy

a = np.array([[ 0 , 1 , 2,  3],
 [ 4,  5,  6,  7],
 [ 8,  9, 10 ,11]])

print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [ ]:
b = a  # Shallow COpy / View 
print(a[0,0])
a[0,0] = 99
print(a[0,0])

print(b)
print(id(a))
print(id(b))

print(b is a)


# deep copy
c =  a.copy()
print(c is a )
print(c is b )

c[0,0] = 999

print(a)
print(c)
print(b)